config/routes.rb
    post '/login' => 'sessions#create', :as => :user_session
    get '/signout' => 'sessions#destroy', :as => :destroy_user_session

    get '/users/cancel' => 'registrations#cancel', :as => :cancel_user_registration
    post '/users' => 'registrations#create', :as => :user_registration
    #get '/get_started' => 'registrations#new', :as => :new_user_registration
    get '/find_caretaker_step/reg' => 'registrations#new', :as => :new_user_registration
    get '/users/password/reset_confirmation' => 'passwords#reset_confirmation', :as => :reset_confirmation
  end

  get '/get_started' => 'find_caretaker_step#index'



  # Registration flow for Caregivers
  %w( basics about_you availability_and_services education_and_experience ).each do |code|
    get "registration/caregiver/#{code.gsub('_', '-')}" => "registration##{code}", :as => code.to_sym
  end


  get 'registration/caregiver' => 'registration#caregiver', as: 'caregiver_registration'
  get 'registration/caregiver/basics/gender' => 'registration#gender', as: 'gender'
  get 'registration/caregiver/basics/birthdate' => 'registration#birthdate', as: 'birthdate'
  get 'registration/caregiver/basics/zipcode' => 'registration#zipcode', as: 'zipcode'
  get 'registration/caregiver/basics/phone' => 'registration#phone', as: 'phone'
  get 'registration/caregiver/basics/language' => 'registration#language', as: 'language'
  get 'registration/caregiver/basics/smoking' => 'registration#smoking', as: 'smoking'
  get 'registration/caregiver/basics/allergies' => 'registration#allergies', as: 'allergies'
  get 'registration/caregiver/basics/pets' => 'registration#pets', as: 'pets'

  get 'registration/caregiver/skills-and-services/work-experience' => 'registration#work_experience', as: 'work_experience'
  get 'registration/caregiver/skills-and-services/skills' => 'registration#skills', as: 'skills'
  get 'registration/caregiver/skills-and-services/services' => 'registration#services', as: 'services'
  get 'registration/caregiver/skills-and-services/hourly_rate' => 'registration#hourly_rate', as: 'hourly_rate'
  get 'registration/caregiver/skills-and-services/live_in' => 'registration#live_in', as: 'live_in'
  get 'registration/caregiver/skills-and-services/schedule' => 'registration#schedule', as: 'schedule'
  get 'registration/caregiver/skills-and-services/credentials' => 'registration#credentials', as: 'credentials'
   get 'registration/caregiver/availability' => 'registration#availability', as: 'availability'

  get 'registration/caregiver/about/hometown' => 'registration#hometown', as: 'hometown'
  get 'registration/caregiver/about/skills' => 'registration#about_skills', as: 'about_skills'
  get 'registration/caregiver/about/me' => 'registration#me', as: 'me'
  get 'registration/caregiver/about/question-1' => 'registration#question_1', as: 'question_1'
  get 'registration/caregiver/about/question-2' => 'registration#question_2', as: 'question_2'
  get 'registration/caregiver/about/question-3' => 'registration#question_3', as: 'question_3'
  get 'registration/caregiver/about/question-4' => 'registration#question_4', as: 'question_4'
  get 'registration/caregiver/about/photo' => 'registration#photo', as: 'photo'
  get 'registration/caregiver/about/background' => 'registration#background', as: 'background'

  patch 'registration/caregiver/update' => "registration#update", :as => :update_caregiver_registration

  # Registration flow for Family
  %w( job payment ).each do |code|
    get "registration/family/#{code.gsub('_', '-')}" => "family_registration##{code}", :as => ("family_" + code).to_sym
  end

  post "registration/family/process-payment" => "family_registration#process_payment", as: :family_process_payment

  patch "registration/family/update" => "family_registration#update", :as => :update_family_registration




  resources :find_caretaker_step do
    collection do
      post :get_started
      get  :caregivers
      get  :care_needs
      get  :schedule
      get  :caretaker
      get  :submit
      get  :reg
      get  :search
      put  :update
    end
  end

  resources :users do
    resources :messages
  end

  resources :messages do
    member do
      post 'read' => 'messages#read', as: 'read'
    end
  end

  resources :caregivers do
    resources :schools, only: [:new, :create, :edit, :update, :delete]
    resources :experiences, only: [:new, :create, :edit, :update, :delete]

    resources :references

    resources :offers do
      post 'add-to-job' => 'offers#add_to_job', as: 'add_to_job'
      get 'apply-to-job' => 'offers#apply_to_job', as: 'apply_to_job'
    end

    get "photo-modal" => "users#photo_modal", :as => :photo_modal, on: :collection

    collection do
      get "edit-profile-modal" => "users#edit_profile_modal"
    end
  end

  get  "photo/modal" => "user_photos#modal"
  post "photo/upload" => "user_photos#upload"
  patch "photo/upload" => "user_photos#upload"
  post "photo/image-process" => "user_photos#image_process"

  resources :offers do
    post 'accept' => 'offers#accept'
  end

  resources :contracts do
    collection do
      post 'search'
    end


    resources :journals
    resources :contacts
    resources :todos
    resources :jobs
    resources :messages
    resources :offers

    member do
      post 'enable' => 'contracts#enable', as: :enable
      post 'disable' => 'contracts#disable', as: :disable
    end
  end

  get "searchjob/show" => "searchjob#show", :as => :searchjob_show
  get "searchjob/hirestep1" => "searchjob#hirestep1", :as => :searchjob_hirestep1
  get "searchjob/hirestep2" => "searchjob#hirestep2", :as => :searchjob_hirestep2
  get "searchjob/create1" => "searchjob#create1", :as => :searchjob_create1
  get "searchjob/create2" => "searchjob#create2", :as => :searchjob_create2



  resources :references do
    collection do
      get 'give-references' => 'references#give_references', :as => :give
    end
  end

  resources :affiliates do
    collection do
      get 'mutual' => 'affiliates#mutual', :as => :mutual
    end
  end

  post "caregivers_search" => "caregivers#search", :as => :caregiver_search

  # caregiver search page can either be near or in zipcode/city

  get "caregivers/near/:zipcode" => "caregivers#near", :as => :near
  get "caregivers/in/:zipcode" => "caregivers#near"

  scope path: "senior-caregivers", controller: 'caregivers', action: 'state_and_city_near' do
    get "/:state/:city", as: :state_and_city_near
  end

  get "dashboard" => "dashboard#show", :as => :dashboard
  get "dashboard/request_references" => "requested_references#request_references", :as => :request_references
  post "dashboard/request_references" => "requested_references#create", :as => :request_references_by_email
  get "dashboard/familyapplication" => "dashboard#familyapplication", :as => :dashboard_familyapplication

  get 'account' => 'users#edit_account', :as => :my_account

  resources :messages, :as => :mailbox, :path => 'mailbox', :only => [:show, :show, :new, :create] do
    collection do
      get 'messages/inbox' => 'messages#inbox', :as => :inbox, :path => 'inbox'
      get 'messages/sentbox' => 'messages#sentbox', :as => :sentbox, :path => 'sentbox'
      get 'messages/trash' => 'messages#trash', as: :trash, path: 'trash'
      resources :cover_letters, path: 'messages/cover-letters'
    end
  end

  get "contacts" => "contacts#show", :as => :contacts
  get "contacts/edit" => "contacts#edit", :as => :contacts_edit

  get "recommendations" => "recommendations#show", :as => :recommendations


  get 'feed' => 'feeds#show', :as => :feed



  get "dashboard/welcome_to_carespotter" => "dashboard#welcome_to_carespotter", :as => :welcome_to_carespotter

  get "add_photo_modal" => "web#add_photo_modal", :as => :add_photo_modal
  get "sign_in_modal" => "web#sign_in_modal", :as => :sign_in_modal
  get "create_job_modal" => "web#create_job_modal", :as => :create_job_modal
  get "create_job_2_modal" => "web#create_job_2_modal", :as => :create_job_2_modal
  get "new_message_modal" => "web#new_message_modal", :as => :new_message_modal
  get "apply_care_job_modal" => "web#apply_care_job_modal", :as => :apply_care_job_modal
  get "reference_request" => "web#reference_request_modal", :as => :reference_request_modal
  get "application_hire_modal" => "web#application_hire_modal", :as => :application_hire_modal
  get "application_msg_modal" => "web#application_msg_modal", :as => :application_msg_modal




  get "cannot_apply" => "web#cannot_apply", :as => :cannot_apply_modal

  get "no_caregiver" => "web#no_caregiver", as: :no_caregiver_modal



  get '/admin' => 'admin#dashboard', as: :admin_dashboard
  get '/admin/caregivers' => 'admin#caregivers', as: :admin_caregivers
  get '/admin/families' => 'admin#families', as: :admin_families
  get '/admin/contracts' => 'admin#contracts', as: :admin_contracts

  post '/admin/:model/add/:id' => 'admin#add', as: :admin_add
  post '/admin/:model/remove/:id' => 'admin#remove', as: :admin_remove
  post '/admin/caregiver/:id' => 'admin#contacted', as: :admin_contacted_caregiver
  post '/admin/contract/:id/remove' => 'admin#remove_contract', as: :admin_remove_contract

  namespace :admin do
    resources :users, only: [:edit, :update]
    resources :experiences, only: [:edit, :update]
    resources :schools, only: [:edit, :update]
    resources :contracts, only: [:edit, :update]
  end

  # if Rails.env.development?
  #   mount MailPreviewController => 'mail_view'
  # end



  # Custom error pages
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code, as: 'error_' + code
  end

  # Static pages for the website
  %w( show about_us how_it_works faq contact privacy terms_of_service team become_a_caregiver unsupported_browser workplace_solutions sign_up payment).each do |page|
    get "web/#{page}", path: page.gsub('_', '-')
  end

  get "/seopage" => 'static#seo'

  get "/sitemap" => 'sitemap#show'

  get "/blog", to: redirect("/blog/")

  root :to => "web#index"

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  around_action :can_view?, except: :welcome_to_carespotter

  def index
    if current_user.caregiver?
      @caregiver = current_user.decorate
    end
  end

  def welcome_to_carespotter
    if current_user.caregiver?
      current_user.congrats_modal = true
      current_user.save!
      render :welcome_to_carespotter_caregiver
    elsif current_user.family?
      current_user.congrats_modal = true
      current_user.save!
      render :welcome_to_carespotter_family
    end
  end

  private

  def can_view?
    if current_user.caregiver?
      yield
    elsif current_user.family?
      redirect_to mailbox_index_path
    else
      redirect_to '/'
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_profile_column.html.erb
<% notice %>

<div class="profile-column">
    <div class="super-box user-photo">
        <%= avatar_tag current_user, :large %>
        <% if current_user.family? && current_user.job %>
            <header class="tc"><%= current_user.job.patient_name %></header>
        <% else %>
            <header class="tc"><%= current_user.first_name %></header>
        <% end %>

        <div class="buttons">
            <%= link_to "Edit Photo", my_account_path %>
        </div>
    </div>

    <div class="super-box quick-links">
        <header class="tc">Quick links</header>
        <div>
            <% if current_user.caregiver? %>
                <%= link_to 'View Profile', caregiver_path(current_user.id) %>
                <%= link_to 'Search Care Jobs', contracts_path %>
                <%= link_to_modal 'Get Recommendations', request_references_path %>
            <% else %>
                <%= link_to 'Search Caregivers', near_path(current_user.zipcode) %>
                <%= link_to 'Edit Job Posting', family_job_path %>
                <%= link_to_modal 'Give Recommendation', give_references_path %>
            <% end %>
        </div>
    </div>

    <% if current_user.family? && current_user.has_job? %>
        <div class="super-box quick-links">
            <header class="tc">Job Offers</header>
            <div>
                <%= link_to 'Manage Job', contract_path(current_user.job.id) %>
                <%= link_to pluralize(current_user.new_offers, "Sent Offer", "Sent Offers"), '#' %>
            </div>
        </div>
    <% end %>
</div>

app/views/dashboard/_profile_header.html.erb
<div class="avatar">
    <%= avatar_tag current_user, :large %>
    <%= link_to_modal photo_path, class: 'edit-btn' do %>
      Edit <span class="mobile-hide">photo</span>
    <% end %>
</div>

<div class="info">
  <div class="headline scroll-hide">
      <h3><%= current_user.first_and_last_initial %></h3>
  </div>

  <div class="user-summary">
    <ul class="stats first columns large-6 small-6">

      <li class="scroll-show">
        <h3><%= current_user.first_and_last_initial %></h3>
      </li>

      <li class="age">
        <strong>Age:</strong> <span><%= current_user.age %></span>
        <%= link_to_modal '', birthdate_path, class: 'edit-btn' %>
      </li>

      <li class="city">
        <strong><%= current_user.city %>, <%= current_user.state %></strong>
        <%= link_to_modal '', zipcode_path, class: 'edit-btn' %>
      </li>

      <li class="experience scroll-hide">
        <strong class="mobile-hide">Experience:</strong>
        <strong class="mobile-show">Exp:</strong> <%= pluralize(current_user.total_experience, "year") %> 
        <%= link_to_modal '', work_experience_path, class: 'edit-btn' %>
      </li>
    </ul>

    <ul class="stats second columns large-6 small-6">

      <li class="experience scroll-show">
        <span class="mobile-hide"><strong>Experience:</strong><%= pluralize(current_user.total_experience, "year") %></span>
        <span class="mobile-show"><strong>Exp:</strong> <%= pluralize(current_user.total_experience, "year") %> </span>
        <%= link_to_modal '', work_experience_path, class: 'edit-btn' %>
      </li>

      <li class="language scroll-mobile-hide">
        <strong>Speaks:</strong> 
        <% if current_user.languages.length > 0 %>
          English, <%= current_user.languages.map { |language| language.name }.join(', ') %>
        <% else %>
          English
        <% end %>
        <%= link_to_modal '', language_path, class: 'edit-btn' %>
      </li>

      <li class="availability scroll-mobile-hide">
        <strong>Availability:</strong>
        <span><%= current_user.availability ? User::Availability.label(current_user.availability) : 'Full Time' %></span>
        <%= link_to_modal '', availability_path, class: 'edit-btn' %>
      </li>

      <li class="live-in-rate scroll-hide">
        <div class="mobile-hide">
          <strong>Live-In Rate:</strong>
          <span class="value"><%= number_to_currency(current_user.live_in_rate, :precision => 0) %></span>
          <span class="hour">/day</span>
          <%= link_to_modal '', live_in_path, class: 'edit-btn' %>
        </div>
        <div class="mobile-show">
          Rate: <%= number_to_currency(current_user.hourly_rate, :precision => 0) %>/hr
          <%= link_to_modal '', hourly_rate_path, class: 'edit-btn' %>
        </div>
      </li>
    </ul>

  </div>
</div>

<div class="profile-buttons">
    <div class="rate">
      <strong><%= number_to_currency(current_user.hourly_rate, :precision => 0) %></strong>/hr
      <%= link_to_modal '', hourly_rate_path, class: 'edit-btn' %>
      <div class="help-bubble mobile-hide">?<span>Caregiver's hourly rate</span></div>
    </div>
    <% if current_user && current_user.family? %>
        <%= link_to_modal 'Contact Me', new_user_message_path(user), class: 'btn main' %>
    <% elsif current_user %>
      <a href='#' class='btn main edit-profile'>
        <span class="preview">Preview <span class="mobile-hide">Profile</span></span>
        <span class="edit">Edit <span class="mobile-hide">Profile</span></span>
      </a>
    <% else %>
      <%= link_to 'Contact Me', new_user_registration_path, class: 'btn main' %>
    <% end %>
</div>

app/views/dashboard/_update_list_item.html.erb
<% if update_list_item.trackable_type == 'Journal' %>
    <%= link_to contract_journals_path(update_list_item.trackable.contract_id), class: 'main-updates' do %>
        <%= avatar_tag update_list_item.trackable.user, :thumb, class: 'small-avatar' %>
        <span class='info'>
            <span class='item-row'>
                <span class="name"><%= update_list_item.trackable.user.first_name %></span>
                <span class="date"><%= update_list_item.created_at.strftime("%m/%d/%Y") %></span>
            </span>

            <span class='item-row'>
                <!--  journal, msg, system, news -->
                <i class='updates-icons journal small'></i>  
                <p>
                    <strong>Journal Entry: </strong>
                    <%= update_list_item.trackable.body %>
                </p>
            </span>
        </span>
    <% end %>
<% elsif update_list_item.trackable_type == 'Notification' %>
    <%= link_to mailbox_path(update_list_item.trackable.conversation.id), class: 'main-updates' do %>
        <%= avatar_tag update_list_item.trackable.sender, :thumb, class: 'small-avatar' %>
        <span class='info'>
            <span class='item-row'>
                <span class="name"><%= update_list_item.trackable.sender.first_name %></span>
                <span class="date"><%= update_list_item.created_at.strftime("%m/%d/%Y") %></span>
            </span>

            <span class='item-row'>
                <i class='updates-icons msg small'></i>

                <p>
                    <strong><%= update_list_item.trackable.conversation.subject %></strong>
                    <%= update_list_item.trackable.body %>
                </p>
            </span>
        </span>
    <% end %>
<% end %>

app/views/dashboard/index.html.erb
<% notice %>

<div class="user-page <%= current_user.should_show_congrats_modal? ? 'congrats-modal-flag' : '' %> <%= current_user.should_show_edit_profile_modal? ? 'edit-profile-modal-flag' : '' %>">
    <div class="caregiver-topbar">
        <div class="caregiver-show-header">
            <div class="banner" style="background-image: url(<%= image_path(current_user.background_path) %>)">
                <%= link_to_modal 'Edit background', background_path, class: 'edit-btn',  id: "background-button"  %>
            </div>
            <div class="container">
                <div class="row user-header">
                    <%= render :partial => 'dashboard/profile_header' %>
                </div>
            </div>
        </div>

        <div class="caregiver-tab-bar">
            <div class="row">
                <ul class="container">
                    <li class="active">
                        <a href="#user-bio">
                            <span class="text">About Me</span><%= image_tag "v2/profile/icon-about.png" %>
                        </a>
                    </li>
                    <li>
                        <a href="#user-education">
                            <span class="text">Education & Experience</span><%= image_tag "v2/profile/icon-edu.png" %>
                        </a>
                    </li>
                    <li class="testimonials">
                        <a href="#user-testimonials">
                            <span class="text">Testimonials</span><span class="count">3</span>
                        </a>
                    </li>
                    <li>
                        <a href="#user-schedule">
                            <span class="text">Availability</span><%= image_tag "v2/profile/icon-cal.png" %>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="columns large-8 small-8 main">
              <div class="section-container auto" data-section="" data-options="one_up: false" style="">
                    <!-- beginning of the work experience section -->
                   <section id="user-bio" class="content <%= (params[:tab] == 'reference' || params[:reference]) ? '' : 'active' %>">
                        <h3>Hi, I'm <%= current_user.first_name.strip %>!</h3>
                         <div>
                            <h4>Why are you a great caregiver?</h4>
                            <div class="wrapper clear">
                              <% if current_user.question_1.blank? %>
                                <%= link_to_modal 'Add Answer', question_1_path, class: 'edit-btn long' %>
                              <% else %>
                                <%= link_to_modal '', question_1_path, class: 'edit-btn' %>
                                <%= current_user.question_1 %>
                              <% end %>
                            </div>
                        </div>
                        <div>
                            <h4>Why did you become a caregiver?</h4>
                            <div class="wrapper clear">
                                <% if current_user.question_2.blank? %>
                                  <%= link_to_modal 'Add Answer', question_2_path, class: 'edit-btn long' %>
                                <% else %>
                                 <%= link_to_modal '', question_2_path, class: 'edit-btn' %>
                                <% end %>
                                <%= current_user.question_2 %>
                            </div>
                            <div>
                            <h4>My top 3 skills as a caregiver are:</h4>
                            <div class="list-item">
                                <div class="wrapper clear">
                                    <% if current_user.has_top_skills? %>
                                      <%= link_to_modal '', about_skills_path, class: 'edit-btn' %>
                                      <%= current_user.top_skills %>
                                    <% else %>
                                      <%= link_to_modal 'Add Answer', about_skills_path, class: 'edit-btn long' %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                        <div>
                            <h4>What are your hobbies and other interests outside of work?</h4>
                            <div class="wrapper clear">
                              <% if current_user.question_3.blank? %>
                                <%= link_to_modal 'Add Answer', question_3_path, class: 'edit-btn long' %>
                              <% else %>
                                <%= link_to_modal '', question_3_path, class: 'edit-btn' %>
                                <%= current_user.question_3 %>
                              <% end %>
                            </div>
                        </div>
                        <div>
                            <h4>What has been your proudest moment or experience as a caregiver?</h4>
                            <div class="wrapper clear">
                              <% if current_user.question_4.blank? %>
                                <%= link_to_modal 'Add Answer', question_4_path, class: 'edit-btn long' %>
                              <% else %>
                                <%= link_to_modal '', question_4_path, class: 'edit-btn' %>
                                <%= current_user.question_4 %>
                              <% end %>
                            </div>
                        </div>
                    </section>

                    <section class="content">
                       <% if current_user.has_skills? or current_user.has_services? or current_user.has_experience_with? %>
                          <div class="simple-list">
                            <h3>Homecare Skills &amp; Services</h3>
                            <h4>Services: </h4>
                            <div class="list-item homecare">
                                <div class="wrapper clear">
                                    <%= link_to_modal '', services_path, class: 'edit-btn' %>
                                    <% if current_user.has_services? %>
                                      <%= current_user.services %>
                                    <% end %>
                                </div>
                            </div>
                            <h4>Experience with:</h4>
                            <div class="list-item homecare">
                                <div class="wrapper clear">
                                    <%= link_to_modal '', skills_path, class: 'edit-btn' %>
                                    <% if current_user.has_experience_with? %>
                                      <%= current_user.experience_with %>
                                    <% end %>
                                </div>
                            </div>
                          </div>
                       <% end %>
                    </section>

                    <section id="user-education" class="education-item content">
                        <h3>Education</h3>
                        <% if current_user.has_education? %>
                            <%= current_user.education_list %>
                        <% end %>
                        <%= link_to_modal '+ Add Education', new_caregiver_school_path(current_user), :class=>'btn' %>
                    </section>

                    <section id="user-experience" class="experience-item content">
                        <h3>Work Experience</h3>
                        <% if current_user.has_experience? %>
                            <%= current_user.experience_list %>
                        <% end %>
                        <%= link_to_modal '+ Add Experience', new_caregiver_experience_path(current_user), :class=>'btn' %>
                    </section>

                  <%= render 'references/caregiver_testimonials' %>

                  <section id="user-schedule" class="content">
                    <%= link_to_modal 'Edit Schedule', schedule_path, class: 'edit-btn' %>
                    <div class="header clear">
                        <h3>Availability</h3>
                        <div class="help-info">
                            <span class="available">Available</span>
                            <span class="unavailable">Unavailable</span>
                        </div>
                    </div>
                    <table>
                      <thead>
                        <tr>
                          <th></th>
                          <% Schedule::DAY.each do |day_key, value| %>
                            <th><%= value[0..2] %></th>
                          <% end %>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                            <th>Morning</th>
                            <%= build_row current_user.schedule, 'morning' %>
                        </tr>
                        <tr>
                            <th>Afternoon</th>
                            <%= build_row current_user.schedule, 'afternoon' %>
                        </tr>
                        <tr>
                            <th>Mid Afternoon</th>
                            <%= build_row current_user.schedule, 'mid_afternoon' %>
                        </tr>
                        <tr>
                            <th>Evening</th>
                            <%= build_row current_user.schedule, 'evening' %>
                        </tr>
                        <tr>
                            <th>Overnight</th>
                            <%= build_row current_user.schedule, 'overnight' %>
                        </tr>
                      </tbody>
                    </table>
                  </section>
            <% if !current_user %>
                <%= link_to_modal 'Contact Me', new_user_registration_path, class: 'btn main' %>
            <% else %>
                <a href="#" class="btn medium edit-profile"><%= image_tag "v2/icon-edit.png" %><span class="preview">Preview Profile</span><span class="edit">Edit Profile</span></a>
            <% end %>
        </div>
        </div>
        <div class="columns large-4 small-4 content side">
            <h3>Quick Facts</h3>
            <div class="facts">
                <div>
                    <%= link_to_modal '', hometown_path, class: 'edit-btn' %>
                    <strong>Hometown:</strong> <%= current_user.hometown %>
                </div>
                <div>
                    <%= link_to_modal '', pets_path, class: 'edit-btn' %>
                    <strong>Pets:</strong> <%= current_user.pets ? User::Pets.label(current_user.pets) : 'None' %>
                </div>
                <div>
                    <%= link_to_modal '', allergies_path, class: 'edit-btn' %>
                    <strong>Allergies:</strong>
                    <%= current_user.allergies_names %>
                </div>
                <div>
                    <%= link_to_modal '', smoking_path, class: 'edit-btn' %>
                    <strong>Smokes:</strong> <%= current_user.smokes ? User::Smokes.label(current_user.smokes) : 'None' %>
                </div>
            </div>

            <!--<ul class="checks">
                <li class="time">Over 50 Care Hours</li>
                <li class="phone">Phone Verified</li>
                <li class="bg">Background Checked</li>
                <li class="doc">Phone Screened</li>
                <li class="lpn">LPN Certified</li>
                <li class="rn">RN Certified</li>
                <li class="cna">CNA Certified</li>
                <li class="cpr">CPR Training</li>
            </ul>-->
        </div>
      </div>
    </div>
</div>

<script type="text/javascript">

var showRegistrationModal = function() {
    var registrationModalDfd = $.ajax({
        url: '/dashboard/welcome_to_carespotter'
    });

    registrationModalDfd.then(function(html) {
        $(html).appendTo('body').modal();
    });
}

var showEditProfileModal = function() {
    var editProfile = $.ajax({
        url: '/caregivers/edit-profile-modal'
     });

    editProfile.then(function(html) {
        $(html).appendTo('body').modal();
        $('.edit-profile-modal').removeClass('edit-profile-modal');
    });
}

if($('.congrats-modal-flag').length > 0) {
    showRegistrationModal();
}

$('.edit-profile').click(function() {
    $('.user-page').toggleClass('edit-mode');

    if($('.edit-profile-modal-flag').length > 0) {
      showEditProfileModal();
    }

    return false;
});

</script>

app/views/dashboard/welcome_to_carespotter_family.html.erb
<div class='welcome-family'>
 
    <%= image_tag 'advisor.png' %>
      <h4>Thank you for creating a job, <%= current_user.first_name %></h4>
    <p>
      Now caregivers will be able to see your care job and apply to you directly
      through Carespotter. You can also contact caregivers directly to invite them
      to apply to your job by clicking Contact Caregiver on their profile.
    </p>
  <div class="buttons">
    <%= link_to 'Start Searching Caregivers', near_path(zipcode: current_user.zipcode), class: 'btn btn-main' %>
  </div>
</div>