config/routes.rb
require 'sidekiq/web'

Carespotter::Application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, :controllers => {
    # sessions: 'sessions',
    # registration: 'registrations',
    passwords: "passwords",
    omniauth_callbacks: 'omniauth_callbacks' },
    skip: [:sessions, :registrations]


  as :user do
    get '/login' => "sessions#new", :as => :new_user_session
    post '/login' => 'sessions#create', :as => :user_session
    get '/signout' => 'sessions#destroy', :as => :destroy_user_session

    get '/users/cancel' => 'registrations#cancel', :as => :cancel_user_registration
    post '/users' => 'registrations#create', :as => :user_registration
    #get '/get_started' => 'registrations#new', :as => :new_user_registration
    get '/find_caretaker_step/reg' => 'registrations#new', :as => :new_user_registration
    get '/users/password/reset_confirmation' => 'passwords#reset_confirmation', :as => :reset_confirmation
  end

  get '/get_started' => 'find_caretaker_step#index'



  # Registration flow for Caregivers
  %w( basics about_you availability_and_services education_and_experience ).each do |code|
    get "registration/caregiver/#{code.gsub('_', '-')}" => "registration##{code}", :as => code.to_sym
  end


  get 'registration/caregiver' => 'registration#caregiver', as: 'caregiver_registration'
  get 'registration/caregiver/basics/gender' => 'registration#gender', as: 'gender'
  get 'registration/caregiver/basics/birthdate' => 'registration#birthdate', as: 'birthdate'
  get 'registration/caregiver/basics/zipcode' => 'registration#zipcode', as: 'zipcode'
  get 'registration/caregiver/basics/phone' => 'registration#phone', as: 'phone'
  get 'registration/caregiver/basics/language' => 'registration#language', as: 'language'
  get 'registration/caregiver/basics/smoking' => 'registration#smoking', as: 'smoking'
  get 'registration/caregiver/basics/allergies' => 'registration#allergies', as: 'allergies'
  get 'registration/caregiver/basics/pets' => 'registration#pets', as: 'pets'

  get 'registration/caregiver/skills-and-services/work-experience' => 'registration#work_experience', as: 'work_experience'
  get 'registration/caregiver/skills-and-services/skills' => 'registration#skills', as: 'skills'
  get 'registration/caregiver/skills-and-services/services' => 'registration#services', as: 'services'
  get 'registration/caregiver/skills-and-services/hourly_rate' => 'registration#hourly_rate', as: 'hourly_rate'
  get 'registration/caregiver/skills-and-services/live_in' => 'registration#live_in', as: 'live_in'
  get 'registration/caregiver/skills-and-services/schedule' => 'registration#schedule', as: 'schedule'
  get 'registration/caregiver/skills-and-services/credentials' => 'registration#credentials', as: 'credentials'
   get 'registration/caregiver/availability' => 'registration#availability', as: 'availability'

  get 'registration/caregiver/about/hometown' => 'registration#hometown', as: 'hometown'
  get 'registration/caregiver/about/skills' => 'registration#about_skills', as: 'about_skills'
  get 'registration/caregiver/about/me' => 'registration#me', as: 'me'
  get 'registration/caregiver/about/question-1' => 'registration#question_1', as: 'question_1'
  get 'registration/caregiver/about/question-2' => 'registration#question_2', as: 'question_2'
  get 'registration/caregiver/about/question-3' => 'registration#question_3', as: 'question_3'
  get 'registration/caregiver/about/question-4' => 'registration#question_4', as: 'question_4'
  get 'registration/caregiver/about/photo' => 'registration#photo', as: 'photo'
  get 'registration/caregiver/about/background' => 'registration#background', as: 'background'

  patch 'registration/caregiver/update' => "registration#update", :as => :update_caregiver_registration

  # Registration flow for Family
  %w( job payment ).each do |code|
    get "registration/family/#{code.gsub('_', '-')}" => "family_registration##{code}", :as => ("family_" + code).to_sym
  end

  post "registration/family/process-payment" => "family_registration#process_payment", as: :family_process_payment

  patch "registration/family/update" => "family_registration#update", :as => :update_family_registration




  resources :find_caretaker_step do
    collection do
      post :get_started
      get  :caregivers
      get  :care_needs
      get  :schedule
      get  :caretaker
      get  :submit
      get  :reg
      get  :search
      put  :update
    end
  end

  resources :users do
    resources :messages
  end

  resources :messages do
    member do
      post 'read' => 'messages#read', as: 'read'
    end
  end

  resources :caregivers do
    resources :schools, only: [:new, :create, :edit, :update, :delete]
    resources :experiences, only: [:new, :create, :edit, :update, :delete]

    resources :references

    resources :offers do
      post 'add-to-job' => 'offers#add_to_job', as: 'add_to_job'
      get 'apply-to-job' => 'offers#apply_to_job', as: 'apply_to_job'
    end

    get "photo-modal" => "users#photo_modal", :as => :photo_modal, on: :collection

    collection do
      get "edit-profile-modal" => "users#edit_profile_modal"
    end
  end

  get  "photo/modal" => "user_photos#modal"
  post "photo/upload" => "user_photos#upload"
  patch "photo/upload" => "user_photos#upload"
  post "photo/image-process" => "user_photos#image_process"

  resources :offers do
    post 'accept' => 'offers#accept'
  end

  resources :contracts do
    collection do
      post 'search'
    end


    resources :journals
    resources :contacts
    resources :todos
    resources :jobs
    resources :messages
    resources :offers

    member do
      post 'enable' => 'contracts#enable', as: :enable
      post 'disable' => 'contracts#disable', as: :disable
    end
  end

  get "searchjob/show" => "searchjob#show", :as => :searchjob_show
  get "searchjob/hirestep1" => "searchjob#hirestep1", :as => :searchjob_hirestep1
  get "searchjob/hirestep2" => "searchjob#hirestep2", :as => :searchjob_hirestep2
  get "searchjob/create1" => "searchjob#create1", :as => :searchjob_create1
  get "searchjob/create2" => "searchjob#create2", :as => :searchjob_create2



  resources :references do
    collection do
      get 'give-references' => 'references#give_references', :as => :give
    end
  end

  resources :affiliates do
    collection do
      get 'mutual' => 'affiliates#mutual', :as => :mutual
    end
  end

  post "caregivers_search" => "caregivers#search", :as => :caregiver_search

  # caregiver search page can either be near or in zipcode/city

  get "caregivers/near/:zipcode" => "caregivers#near", :as => :near
  get "caregivers/in/:zipcode" => "caregivers#near"

  scope path: "senior-caregivers", controller: 'caregivers', action: 'state_and_city_near' do
    get "/:state/:city", as: :state_and_city_near
  end

  get "dashboard" => "dashboard#show", :as => :dashboard
  get "dashboard/request_references" => "requested_references#request_references", :as => :request_references
  post "dashboard/request_references" => "requested_references#create", :as => :request_references_by_email
  get "dashboard/familyapplication" => "dashboard#familyapplication", :as => :dashboard_familyapplication

  get 'account' => 'users#edit_account', :as => :my_account

  resources :messages, :as => :mailbox, :path => 'mailbox', :only => [:show, :show, :new, :create] do
    collection do
      get 'messages/inbox' => 'messages#inbox', :as => :inbox, :path => 'inbox'
      get 'messages/sentbox' => 'messages#sentbox', :as => :sentbox, :path => 'sentbox'
      get 'messages/trash' => 'messages#trash', as: :trash, path: 'trash'
      resources :cover_letters, path: 'messages/cover-letters'
    end
  end

  get "contacts" => "contacts#show", :as => :contacts
  get "contacts/edit" => "contacts#edit", :as => :contacts_edit

  get "recommendations" => "recommendations#show", :as => :recommendations


  get 'feed' => 'feeds#show', :as => :feed



  get "dashboard/welcome_to_carespotter" => "dashboard#welcome_to_carespotter", :as => :welcome_to_carespotter

  get "add_photo_modal" => "web#add_photo_modal", :as => :add_photo_modal
  get "sign_in_modal" => "web#sign_in_modal", :as => :sign_in_modal
  get "create_job_modal" => "web#create_job_modal", :as => :create_job_modal
  get "create_job_2_modal" => "web#create_job_2_modal", :as => :create_job_2_modal
  get "new_message_modal" => "web#new_message_modal", :as => :new_message_modal
  get "apply_care_job_modal" => "web#apply_care_job_modal", :as => :apply_care_job_modal
  get "reference_request" => "web#reference_request_modal", :as => :reference_request_modal
  get "application_hire_modal" => "web#application_hire_modal", :as => :application_hire_modal
  get "application_msg_modal" => "web#application_msg_modal", :as => :application_msg_modal




  get "cannot_apply" => "web#cannot_apply", :as => :cannot_apply_modal

  get "no_caregiver" => "web#no_caregiver", as: :no_caregiver_modal



  get '/admin' => 'admin#dashboard', as: :admin_dashboard
  get '/admin/caregivers' => 'admin#caregivers', as: :admin_caregivers
  get '/admin/families' => 'admin#families', as: :admin_families
  get '/admin/contracts' => 'admin#contracts', as: :admin_contracts

  post '/admin/:model/add/:id' => 'admin#add', as: :admin_add
  post '/admin/:model/remove/:id' => 'admin#remove', as: :admin_remove
  post '/admin/caregiver/:id' => 'admin#contacted', as: :admin_contacted_caregiver
  post '/admin/contract/:id/remove' => 'admin#remove_contract', as: :admin_remove_contract

  namespace :admin do
    resources :users, only: [:edit, :update]
    resources :experiences, only: [:edit, :update]
    resources :schools, only: [:edit, :update]
    resources :contracts, only: [:edit, :update]
  end

  # if Rails.env.development?
  #   mount MailPreviewController => 'mail_view'
  # end



  # Custom error pages
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code, as: 'error_' + code

app/controllers/family_registration_controller.rb
require 'braintree'

class FamilyRegistrationController < ApplicationController

	before_action :authenticate_user!
	before_action :verify_family!


	def job
	  @job = current_user.find_or_create_job
	end

  def payment
    @client_token = Braintree::ClientToken.generate(
      :customer_id => current_user.customer_id
    )
  end

  def process_payment
    result = Braintree::Transaction.sale(
      amount: "99.00",
      payment_method_nonce: params[:payment_method_nonce],
      options: {
        submit_for_settlement: true
      }
    )

    job = current_user.job
    job.indexable = true
    job.save!

    redirect_to inbox_mailbox_index_path
  end

	def update
		if job_params
			@job = current_user.find_or_create_job

			if @job.update(job_params)
      			current_user.update!(zipcode: @job.zipcode, phone: @job.phone)
      			redirect_to near_path(zipcode: @job.zipcode), notice: 'Your job has been created'
    		else
      			render action: :job
    		end
		elsif user_params
			if current_user.update!(user_params)
				redirect_to near_path(current_user.zipcode), notice: 'You have finished registratio'
			else
				render action :shared_connections
			end
		else
			redirect_to near_path(current_user.job.zipcode)
		end
	end

	private

	def job_params
		params[:contract].permit(
            :age_range, :hourly_type, :care_type,
            :schedule_type, :schedule_need, :gender,
            :patient_name, :headline, :description, :hours_needed,
            :zipcode, :phone, :job_type, :required_rate,
            screening_questions_attributes: [ :question ],
            service_ids: [], requirement_ids: []) unless params[:contract].nil?
	end

	def user_params
		params[:user].permit(affiliate_ids: []) unless params[:user].nil?
	end
end

app/views/family_registration/_sidebar.html.erb
<nav class="user-navigator">
    <div class="sidebar-scrolling">
        <ul>
            <li>
                <%= link_to family_job_path, class: current_step == 'create_job' ? 'act': '' do %>
                    <i class="createjob"></i><span>Create Job</span>
                    <% if current_step == 'create_job' %>
                        <%= content_tag(:i, '', class: 'act-arrow') %>
                    <% end %>
                <% end %>
            </li>
            <li>
                <%= link_to family_shared_connections_path, class: current_step == 'shared_connections' ? 'act': '' do %>
                    <i class="sharedconnections"></i><span>Shared Connections</span>
                    <% if current_step == 'shared_connections' %>
                        <%= content_tag(:i, '', class: 'act-arrow') %>
                    <% end %>
                <% end %>
            </li>
        </ul>
    </div>
</nav>

app/views/family_registration/job.html.erb
<div class="user-edit-page family-job-register <%= @job.has_been_edited ? 'edit-job' : 'new-job' %>">

    <div class="row">

        <% if @job.errors.any? %>
            <div id="error_explanation">
                <div>
                    <ul>
                        <% @job.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        <% end %>

        <header>
            <h2>Hi <%= current_user.first_name %>,<br class="mobile-show" /> welcome to Carespotter</h2>
            <p>Let's learn a little more about your caregiving needs to match you with the right caregivers. <span class="mobile-hide">This care evaluation only takes a few minutes and helps us best understand how to match you with the best caregiver who meets your family's requirements and availability.</span></p>
        </header>

        <%= form_for @job, url: update_family_registration_path, method: 'patch' do |f| %>

            <%= render partial: 'jobs/form2', locals: {f: f} %>

            <%= f.submit 'Submit Job', class: 'btn' %>
            <a href="#">Save and finish later</a>
        <% end %>

    </div>
</div>

<!-- Google Code for Family Job Registration Conversion Page -->
<script type=“text/javascript”>
/* <![CDATA[ */
var google_conversion_id = 1036789869;
var google_conversion_language = “en”;
var google_conversion_format = “2”;
var google_conversion_color = “ffffff”;
var google_conversion_label = “ekZTCK2eoVkQ7dCw7gM”;
var google_remarketing_only = false;
/* ]]> */
</script>
<script type=“text/javascript”
src=“//www.googleadservices.com/pagead/conversion.js”>
</script>
<noscript>
<div style=“display:inline;”>
<img height=“1” width=“1” style=“border-style:none;” alt=“”
src=“//www.googleadservices.com/pagead/conversion/1036789869/?label=ekZTCK2eoVkQ7dCw7gM&amp;guid=ON&amp;script=0”/>
</div>
</noscript>

app/views/family_registration/payment.html.erb
<%= form_tag family_process_payment_path, id: 'checkout', method: 'POST' do %>
  <div id='dropin'></div>
  <%= submit_tag 'Submit & Pay', class: 'btn main' %>
<% end %>

<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<script>

braintree.setup(
  '<%= "#{@client_token}" %>',
  'dropin', {
    container: 'dropin'
  });


</script>

app/views/family_registration/shared_connections.html.erb
<div class="user-edit-page container-large">
    <div class="row">


        <div class="content">
            <div class="row">
                <%= form_for current_user, url: update_family_registration_path, method: 'patch' do |f| %>

                    <header>
                        <h2>Payment</h2>
                    </header>


                    <%= f.submit 'Complete Job Posting', class: 'btn main' %>

                <% end %>

            </div>
        </div>
    </div>
</div>