config/routes.rb
    post '/login' => 'sessions#create', :as => :user_session
    get '/signout' => 'sessions#destroy', :as => :destroy_user_session

    get '/users/cancel' => 'registrations#cancel', :as => :cancel_user_registration
    post '/users' => 'registrations#create', :as => :user_registration
    #get '/get_started' => 'registrations#new', :as => :new_user_registration
    get '/find_caretaker_step/reg' => 'registrations#new', :as => :new_user_registration
    get '/users/password/reset_confirmation' => 'passwords#reset_confirmation', :as => :reset_confirmation
  end

  get '/get_started' => 'find_caretaker_step#index'



  # Registration flow for Caregivers
  %w( basics about_you availability_and_services education_and_experience ).each do |code|
    get "registration/caregiver/#{code.gsub('_', '-')}" => "registration##{code}", :as => code.to_sym
  end


  get 'registration/caregiver' => 'registration#caregiver', as: 'caregiver_registration'
  get 'registration/caregiver/basics/gender' => 'registration#gender', as: 'gender'
  get 'registration/caregiver/basics/birthdate' => 'registration#birthdate', as: 'birthdate'
  get 'registration/caregiver/basics/zipcode' => 'registration#zipcode', as: 'zipcode'
  get 'registration/caregiver/basics/phone' => 'registration#phone', as: 'phone'
  get 'registration/caregiver/basics/language' => 'registration#language', as: 'language'
  get 'registration/caregiver/basics/smoking' => 'registration#smoking', as: 'smoking'
  get 'registration/caregiver/basics/allergies' => 'registration#allergies', as: 'allergies'
  get 'registration/caregiver/basics/pets' => 'registration#pets', as: 'pets'

  get 'registration/caregiver/skills-and-services/work-experience' => 'registration#work_experience', as: 'work_experience'
  get 'registration/caregiver/skills-and-services/skills' => 'registration#skills', as: 'skills'
  get 'registration/caregiver/skills-and-services/services' => 'registration#services', as: 'services'
  get 'registration/caregiver/skills-and-services/hourly_rate' => 'registration#hourly_rate', as: 'hourly_rate'
  get 'registration/caregiver/skills-and-services/live_in' => 'registration#live_in', as: 'live_in'
  get 'registration/caregiver/skills-and-services/schedule' => 'registration#schedule', as: 'schedule'
  get 'registration/caregiver/skills-and-services/credentials' => 'registration#credentials', as: 'credentials'
   get 'registration/caregiver/availability' => 'registration#availability', as: 'availability'

  get 'registration/caregiver/about/hometown' => 'registration#hometown', as: 'hometown'
  get 'registration/caregiver/about/skills' => 'registration#about_skills', as: 'about_skills'
  get 'registration/caregiver/about/me' => 'registration#me', as: 'me'
  get 'registration/caregiver/about/question-1' => 'registration#question_1', as: 'question_1'
  get 'registration/caregiver/about/question-2' => 'registration#question_2', as: 'question_2'
  get 'registration/caregiver/about/question-3' => 'registration#question_3', as: 'question_3'
  get 'registration/caregiver/about/question-4' => 'registration#question_4', as: 'question_4'
  get 'registration/caregiver/about/photo' => 'registration#photo', as: 'photo'
  get 'registration/caregiver/about/background' => 'registration#background', as: 'background'

  patch 'registration/caregiver/update' => "registration#update", :as => :update_caregiver_registration

  # Registration flow for Family
  %w( job payment ).each do |code|
    get "registration/family/#{code.gsub('_', '-')}" => "family_registration##{code}", :as => ("family_" + code).to_sym
  end

  post "registration/family/process-payment" => "family_registration#process_payment", as: :family_process_payment

  patch "registration/family/update" => "family_registration#update", :as => :update_family_registration




  resources :find_caretaker_step do
    collection do
      post :get_started
      get  :caregivers
      get  :care_needs
      get  :schedule
      get  :caretaker
      get  :submit
      get  :reg
      get  :search
      put  :update
    end
  end

  resources :users do
    resources :messages
  end

  resources :messages do
    member do
      post 'read' => 'messages#read', as: 'read'
    end
  end

  resources :caregivers do
    resources :schools, only: [:new, :create, :edit, :update, :delete]
    resources :experiences, only: [:new, :create, :edit, :update, :delete]

    resources :references

    resources :offers do
      post 'add-to-job' => 'offers#add_to_job', as: 'add_to_job'
      get 'apply-to-job' => 'offers#apply_to_job', as: 'apply_to_job'
    end

    get "photo-modal" => "users#photo_modal", :as => :photo_modal, on: :collection

    collection do
      get "edit-profile-modal" => "users#edit_profile_modal"
    end
  end

  get  "photo/modal" => "user_photos#modal"
  post "photo/upload" => "user_photos#upload"
  patch "photo/upload" => "user_photos#upload"
  post "photo/image-process" => "user_photos#image_process"

  resources :offers do
    post 'accept' => 'offers#accept'
  end

  resources :contracts do
    collection do
      post 'search'
    end


    resources :journals
    resources :contacts
    resources :todos
    resources :jobs
    resources :messages
    resources :offers

    member do
      post 'enable' => 'contracts#enable', as: :enable
      post 'disable' => 'contracts#disable', as: :disable
    end
  end

  get "searchjob/show" => "searchjob#show", :as => :searchjob_show
  get "searchjob/hirestep1" => "searchjob#hirestep1", :as => :searchjob_hirestep1
  get "searchjob/hirestep2" => "searchjob#hirestep2", :as => :searchjob_hirestep2
  get "searchjob/create1" => "searchjob#create1", :as => :searchjob_create1
  get "searchjob/create2" => "searchjob#create2", :as => :searchjob_create2



  resources :references do
    collection do
      get 'give-references' => 'references#give_references', :as => :give
    end
  end

  resources :affiliates do
    collection do
      get 'mutual' => 'affiliates#mutual', :as => :mutual
    end
  end

  post "caregivers_search" => "caregivers#search", :as => :caregiver_search

  # caregiver search page can either be near or in zipcode/city

  get "caregivers/near/:zipcode" => "caregivers#near", :as => :near
  get "caregivers/in/:zipcode" => "caregivers#near"

  scope path: "senior-caregivers", controller: 'caregivers', action: 'state_and_city_near' do
    get "/:state/:city", as: :state_and_city_near
  end

  get "dashboard" => "dashboard#show", :as => :dashboard
  get "dashboard/request_references" => "requested_references#request_references", :as => :request_references
  post "dashboard/request_references" => "requested_references#create", :as => :request_references_by_email
  get "dashboard/familyapplication" => "dashboard#familyapplication", :as => :dashboard_familyapplication

  get 'account' => 'users#edit_account', :as => :my_account

  resources :messages, :as => :mailbox, :path => 'mailbox', :only => [:show, :show, :new, :create] do
    collection do
      get 'messages/inbox' => 'messages#inbox', :as => :inbox, :path => 'inbox'
      get 'messages/sentbox' => 'messages#sentbox', :as => :sentbox, :path => 'sentbox'
      get 'messages/trash' => 'messages#trash', as: :trash, path: 'trash'
      resources :cover_letters, path: 'messages/cover-letters'
    end
  end

  get "contacts" => "contacts#show", :as => :contacts
  get "contacts/edit" => "contacts#edit", :as => :contacts_edit

  get "recommendations" => "recommendations#show", :as => :recommendations


  get 'feed' => 'feeds#show', :as => :feed



  get "dashboard/welcome_to_carespotter" => "dashboard#welcome_to_carespotter", :as => :welcome_to_carespotter

  get "add_photo_modal" => "web#add_photo_modal", :as => :add_photo_modal
  get "sign_in_modal" => "web#sign_in_modal", :as => :sign_in_modal
  get "create_job_modal" => "web#create_job_modal", :as => :create_job_modal
  get "create_job_2_modal" => "web#create_job_2_modal", :as => :create_job_2_modal
  get "new_message_modal" => "web#new_message_modal", :as => :new_message_modal
  get "apply_care_job_modal" => "web#apply_care_job_modal", :as => :apply_care_job_modal
  get "reference_request" => "web#reference_request_modal", :as => :reference_request_modal
  get "application_hire_modal" => "web#application_hire_modal", :as => :application_hire_modal
  get "application_msg_modal" => "web#application_msg_modal", :as => :application_msg_modal




  get "cannot_apply" => "web#cannot_apply", :as => :cannot_apply_modal

  get "no_caregiver" => "web#no_caregiver", as: :no_caregiver_modal



  get '/admin' => 'admin#dashboard', as: :admin_dashboard
  get '/admin/caregivers' => 'admin#caregivers', as: :admin_caregivers
  get '/admin/families' => 'admin#families', as: :admin_families
  get '/admin/contracts' => 'admin#contracts', as: :admin_contracts

  post '/admin/:model/add/:id' => 'admin#add', as: :admin_add
  post '/admin/:model/remove/:id' => 'admin#remove', as: :admin_remove
  post '/admin/caregiver/:id' => 'admin#contacted', as: :admin_contacted_caregiver
  post '/admin/contract/:id/remove' => 'admin#remove_contract', as: :admin_remove_contract

  namespace :admin do
    resources :users, only: [:edit, :update]
    resources :experiences, only: [:edit, :update]
    resources :schools, only: [:edit, :update]
    resources :contracts, only: [:edit, :update]
  end

  # if Rails.env.development?
  #   mount MailPreviewController => 'mail_view'
  # end



  # Custom error pages
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code, as: 'error_' + code
  end

  # Static pages for the website
  %w( show about_us how_it_works faq contact privacy terms_of_service team become_a_caregiver unsupported_browser workplace_solutions sign_up payment).each do |page|
    get "web/#{page}", path: page.gsub('_', '-')
  end

  get "/seopage" => 'static#seo'

  get "/sitemap" => 'sitemap#show'

  get "/blog", to: redirect("/blog/")

  root :to => "web#index"

app/controllers/searchjob_controller.rb
require_dependency "zip_code_converter"

class SearchjobController < ApplicationController
	before_action :authenticate_user!
	before_action :set_dashboard

	def index

	end

	def show

	end

	def hirestep1

	end

	def hirestep2

	end

	def create1
	end

	def create2
	end

end

app/views/searchjob/_contract_on_search.html.erb
<section class="super-main on-list">

    <h4>
        <%= contract_on_search.headline %>

        <% if current_user.applied_for_contract? contract_on_search %>
            <span class="applied-job">Applied<i></i></span>
        <% else %>
            <% if current_user.completed_profile? && current_user.indexable %>
                <%= link_to_modal 'Apply', caregiver_offer_apply_to_job_path(current_user.id, contract_on_search.id, contract_id: contract_on_search.id), class: 'btn main apply-to-job' %>
            <% else %>
                <%= link_to_modal 'Apply', cannot_apply_modal_path, class: 'btn main' %>
            <% end %>
        <% end %>
    </h4>

    <table class="details">
        <tr>
            <td class="first-col">
                <strong>Job posted on:</strong> <%= contract_on_search.created_at.strftime("%m/%d/%Y") %>
            </td>
        </tr>
        <tr>
            <td class="first-col">
                <%= contract_on_search.schedule_to_label %>
                <strong>Schedule:</strong> <%= contract_on_search.schedule_to_label %>
            </td>
            <td class="second-col">
                <strong>Hourly rate:</strong><span class="blue strong">from $<%= contract_on_search.required_rate %></span>
            </td>
        </tr>
        <tr>
            <td class="first-col" colspan="2">
                <strong>Requirements:</strong>
                <ul>
                    <% if contract_on_search.has_services? %>
                        <% contract_on_search.services.each do |service| %>
                            <li><%= service.name %></li>
                        <% end %>
                    <% else %>
                        <li>None</li>
                    <% end %>
                </ul>
            </td>
        </tr>
         <tr>
            <td class="first-col" colspan="2">
                <strong>Need help with:</strong>
                <ul>
                    <% if contract_on_search.has_requirements? %>
                        <% contract_on_search.requirements.each do |requirements| %>
                            <li><%= requirements.name %></li>
                        <% end %>
                    <% else %>
                        <li>None</li>
                    <% end %>
                </ul>
            </td>
        </tr>
    </table>

    <div class="information">
        <p>
            <%= contract_on_search.description %>

            <% if current_user.applied_for_contract? contract_on_search %>
                <%= link_to 'Read More', contract_path(current_user.offer_for_contract(contract_on_search).contract_id), class: 'read-more' %>
            <% end %>
        </p>
    </div>

</section>

app/views/searchjob/_contract_on_search2.html.erb
<section class="job-item">

    <div class="main-info">
        <h3>
            <%= link_to contract_on_search.headline, contract_path(contract_on_search) %>
        </h3>

        <p class="descr">
            <%= contract_on_search.description %>

            <% if current_user.applied_for_contract? contract_on_search %>
                <%= link_to 'More', contract_path(current_user.offer_for_contract(contract_on_search).contract_id), class: 'more' %>
            <% end %>
        </p>

        <div class="requirements">
            <div class="special">
                <label>Special request:</label>
                <ul>
                    <li>Needed a caregiver ASAP</li>
                </ul>
            </div>
            <div>
                <label>Requirements:</label>
                <ul>
                    <% if contract_on_search.has_services? %>
                        <% contract_on_search.services.each do |service| %>
                            <li><%= service.name %></li>
                        <% end %>
                    <% else %>
                        <li>None</li>
                    <% end %>
                </ul>
            </div>
        </div>

    </div>

    <div class="details">
        <div class="header">
            <h5 class="hourly-rate"><%= number_to_currency(contract_on_search.required_rate, precision: 0) %>/<%= abbr_time(contract_on_search.hourly_type) || 'hr' %></h5>
            <h6><span class="distance"><%=
            miles_away_label_contract(contract_on_search, current_user.zipcode)
            %></span></h6>
        </div>
        <ul class="stats">
            <li>Schedule: <%= contract_on_search.hours_needed_schedule %></li>
            <% if contract_on_search.updated_at >= 2.weeks.ago %>
                <li class="red">New Posting! <%= contract_on_search.updated_at.strftime("%m/%d/%Y") %></li>
            <% else %>
                <li>Posted: <%= contract_on_search.updated_at.strftime("%m/%d/%Y") %></li>
            <% end %>
        </ul>
        <% if current_user.completed_profile? && current_user.indexable %>
            <%= link_to 'Read More', contract_path(id: contract_on_search.id), class: 'btn btn-main' %>
        <% else %>
            <%= link_to 'Read More', cannot_apply_modal_path, class: 'btn btn main' %>
        <% end %>
    </div>

</section>

app/views/searchjob/_create_sidebar.html.erb
<nav class="user-navigator">
    <div class="sidebar-scrolling">
        <ul>
            <li>
                <%= link_to family_job_path, class: current_step == 'create_job' ? 'act': '' do %>
                    <i class="createjob"></i><span>Create Job</span>
                    <% if current_step == 'create_job' %>
                        <%= content_tag(:i, '', class: 'act-arrow') %>
                    <% end %>
                <% end %>
            </li>
            <li>
                <%= link_to family_shared_connections_path, class: current_step == 'shared_connections' ? 'act': '' do %>
                    <i class="sharedconnections"></i><span>Shared Connections</span>
                    <% if current_step == 'shared_connections' %>
                        <%= content_tag(:i, '', class: 'act-arrow') %>
                    <% end %>
                <% end %>
            </li>
        </ul>
    </div>
</nav>

app/views/searchjob/_hireprogress.html.erb
<!-- if 2 steps complete add class "two-steps", if 3 steps "three-steps" -->
<div class="hire-progres two-steps">

	<!-- if complete add class "complete" -->
	<a class="step first complete">
		<span>1</span>
		<p>Sign In</p>
	</a>

	<a class="step middle complete">
		<span>2</span>
		<p>Offer details</p>
	</a>

	<a class="step last">
		<span>3</span>
		<p>Review offer</p>
	</a>

</div>

app/views/searchjob/createorganization_modal.html.erb
<header>
	Request for new organization
</header>

<div class="body middle-width">

	<form method="post" action="#" class="myform" id="create-organization">
		<div class="field">
			<label>Enter the name of community group you would like to add.</label>
			<input type="text" placeholder="South" placeholder: 'For example: Downtown YMCA, Orlando Rotary Club, ect'>
		</div>
		<div class="action">
			<input type="submit" class="btn main" value="Save">
		</div>
	</form>

</div>

app/views/searchjob/show.html.erb
<div class="dashboard-page container-large">
    <div class="row">

        <div class="content main-cnt">
            <div class="row">

                <header>
                    <h2>Dashboard</h2>
                </header>

                <%= render partial: 'dashboard/profile_column' %>

                <div class="content-column">

                	<%= render partial: 'dashboard/alerts' %>

                    <div class="super-box search-job with-search-header">

                        <header class="with-bg">
                            54 Orlando Care Jobs near 32708
                            <form action="#" method="post">
                                <button class="btn main">
                                    <span class="icon-search"></span>
                                </button>
                                <input type="text" name="query" placeholder="zip code or city">
                            </form>
                        </header>

                        <section class="super-main">
                            <a href="#" class="back-to-prev"><span></span>Return to Search Page</a>

                            <h4>
                                Daughter needs part-time help caring for mother
                                <span class="applied-job">Applied<i></i></span>
                            </h4>

                            <div class="location">
                                <strong>Location:</strong>Orlando, Florida, 32801
                            </div>

                            <table class="details">
                                <tr>
                                    <td class="first-col" colspan="2">
                                        <strong>Job posted on:</strong> September 10. 2013
                                    </td>
                                </tr>
                                <tr>
                                    <td class="first-col">
                                        <strong>Schedule:</strong> Hourly Only
                                    </td>
                                    <td class="second-col">
                                        <strong>Hourly rate:</strong><span class="blue strong">from $10</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="first-col" colspan="2">
                                        <strong>Requirements:</strong>
                                        <ul>
                                            <li>Transfer Assistance</li>
                                            <li>Toileting and Incontinence</li>
                                            <li>Tracheotomy Care</li>
                                        </ul>
                                    </td>
                                </tr>
                                 <tr>
                                    <td class="first-col" colspan="2">
                                        <strong>Need help with:</strong>
                                        <ul>
                                            <li>Transfer Assistance</li>
                                            <li>Toileting and Incontinence</li>
                                            <li>Tracheotomy Care</li>
                                            <li>Transfer Assistance</li>
                                            <li>Transfer Assistance</li>
                                        </ul>
                                    </td>
                                </tr>
                            </table>

                            <div class="information">
                                <h6>Additional Information</h6>
                                <p>I am 37 years old with 10 years of caregiving experience i am planning on getting my CNA sometime soon. I am very dedicated to my clients and their well-being. I am dependable if you needed me for something last minute more than likely be able to help. I am very respectful of people and their emotions. I have a habit of putting others first, which I find to be good. I have a lot of patience for people, everything takes time. I love to reorganize and to keep things in a simple and easy way to find. Cooking is always fun especially finding new ways to keep it healthy. I believe communication is key, wether it's just listening to a story or instructions they are just as important. Making sure every situation is a safe environment safety is number one.
                                </p>
                            </div>

                        </section>

                        <div class="foot">
                            <%= link_to_modal 'Apply now', apply_care_job_modal_path, class: 'btn main' %>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>